src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts
BRS-167
https://bcmines.atlassian.net/browse/BRS-167
This change prevents timeslots from displaying if the facility does not offer them (`AM`, `PM`, `DAY`). The field 'offered' is added to the 'timeConfig' object and checks whether that particular timeslot is offered. Timeslots that are offered but unavailable because they are full are still shown as disabled.
=> BRS-167: hide daypass times that are not offered

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
BRS-219
https://bcparksdigital.atlassian.net/browse/BRS-219
Updating the cloudfront distribution can take 2+ minutes (up to 25 or so), during which some edge locations will try to access the new content, even if it hasn't been uploaded to S3 yet.
Note this creates a potential problem if we change the S3 bucket name, since the bucket is managed by terragrunt which is now run after the upload. I haven't found a solution for that - it shouldn't be something that happens often though.
Also format actions files with prettier.
=> BRS-219: upload to s3 before updating cloudfront distribution

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts
NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-294 added API functionality to prevent AM passes from being created if the AM time slot had already transpired (trying to book an AM pass after 12pm on the same day). The API will now correctly deny users who try to do this - however, the AM slot still shows available on the public side and users will go through the whole workflow before they are told by the API their booking is not possible. This change disables the AM slot on the public front end if the current time is beyond the PM time slot opening time (12pm).
=> NOBUG: disable AM slot if beyond AM time

src/app/pass-lookup/pass-lookup.component.ts, src/app/shared/components/alert/alert.component.html, src/app/shared/components/alert/alert.module.ts
BRS-296
https://bcparksdigital.atlassian.net/browse/BRS-296
This change displays the date and time of day of a pass to the front end if it was successfully cancelled. Note: this change requires https://github.com/bcgov/parks-reso-api/pull/91 in order to work.
Recommend approving https://github.com/bcgov/parks-reso-api/pull/91 first and doing testing with `dev` API, as there are many gotchas with running cancellation workflows in the `local` env when GCNotify is involved.
=> BRS-296 show date after successful booking cancellation

package.json, yarn.lock
NOBUG
Upgrading ng-bootstrap to 10. 9 is not compatible with angular 12.
=> NOBUG: Updating ng-bootstrap to 10.

package.json, src/app/registration/facility-select/facility-select.component.ts, src/app/registration/registration-details/registration-details.component.html, src/app/registration/registration.component.ts, src/app/shared/components/date-picker/date-picker.component.ts, src/app/shared/utils/utils.ts, yarn.lock
BRS-656
https://bcparksdigital.atlassian.net/browse/BRS-656
This change ensures that the front-end datepicker always resides in the PST/PDT timezone 'America/Vancouver'. Previously, the dates shown were influenced by the browser's local timezone, sometimes resulting in the wrong days being displayed. This change leverages the datetime package `luxon` to handle timezone offsets. The front end now always shows dates as they would be at that instant in PST/PDT. Dates are passed to the back-end as UTC ISO time format for 12:00 noon PST/PDT on the selected booking date. 
Dates shown in other parts of the app have been formatted to display in PST/PDT where appropriate. 
This change will be accompanied in the future by changes to the API/back-end such that they will also handle dates properly; …
=> BRS-656: fixing datepicker to PST

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts, src/app/shared/components/date-picker/date-picker.component.html, src/app/shared/components/date-picker/date-picker.component.ts
BRS-656
https://bcparksdigital.atlassian.net/browse/BRS-656
Setting browser timezone to U+14 caused the datepicker to indicate that 'today' was tomorrow, though no actual date was selected (datepicker with `null` date). There is no way to prevent datepicker from assuming today's date based on the local browser time, so now when selecting a pass, today's date (in PST) is prepopulated when the form is initialized. This way, there is never a `null` date in the datepicker.
=> BRS-656 initializing today in datepicker

src/app/registration/facility-select/facility-select.component.ts
BRS-812
https://bcparksdigital.atlassian.net/browse/BRS-812
This forces luxon to use en-CA locale, instead of whatever the user's locale is.
=> BRS-812: Fix for language setting - override browser.

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-pr.yaml
NOBUG
Upgrading GH actions to run Node16.
https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/
=> NOBUG - upgrading GH Actions to Node16

terraform/src/cloudfront.tf
BRS-911
https://bcparksdigital.atlassian.net/browse/BRS-911
Updating our S3 Asset Cloudfront distribution to have the same `blacklist` rules as our public front end distribution.
=> BRS-911: Updating S3 Assets distribution blacklist

src/app/registration/park-details/park-details.component.html
fixes #262 
BRS-262
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=38951146
Updated the hyperlink text to be "BC Parks page" instead of "here".
=> BRS-262: Changed hyperlink text on Park details to align with new format

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts
BRS-280
[https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42572823](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42572823)
Text change to change the reservation times to reflect noon instead of 1pm.
=> BRS:280 - Update front end for end of daylight savings

terraform/prod/terragrunt.hcl
NOBUG
Due to the wildcard cert causing problems with `*bcparks.ca` domains, DUP's certificates were recently upgraded to be more specific. DUP CloudFront no longer contains a wildcard certificate for `*bcparks.ca`, rather, it has `reserve.bcparks.ca` for DUP public and `reserve-admin.bcparks.ca` for DUP admin. The added complexity of doing this in Go Daddy vs Route53 has forced us to remove the other vanity url for DUP public, `parkingpass.bcparks.ca`. 
Terraform had this removed url hardcoded in its build files and would bomb when the ACM Cert ARN that it pulled didnt support `parkingpass.bcparks.ca`. This ticket is to remove that hardcode. Another ticket will have to be created to investigate the feasibility of reintroducing this vanity url if necessary.
=> Removing 'parkingpass.bcparks.ca' as a vanity url

src/app/registration/contact-form/contact-form.component.ts
BRS-309
[BRS-309](https://github.com/bcgov/parks-reso-public/issues/309)
Form defaults to not requiring phone numbers when loaded.
When phone number is not required: Do not include phone number prefix in post. This will prevent trying to send SMS to "+" as a number.
=> BRS-309: Mandatory Phone number bug

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss
BRS-348
#348 
- Increase the size of the checkbox to the specified 44px height and width
- Fix issues with text overlapping / wrapping beneath the checkbox - should be cleaner on mobile all around.
- Moved the label text for #enablePhone checkbox back into the <label> parent for accessibility, easier to click
=> BRS-348: Increase checkbox size, fix mobile issues

src/app/registration/success/success.component.html
BRS-341
#341 
Fix two typos in the "Next steps" section of the success page.
- Replacing "via" with "by"
- Missing comma
=> BRS-341 FIX: Typo fixes for Success page

src/app/registration/success/success.component.spec.ts, src/app/registration/success/success.component.ts
BRS-323
#323
Fix an issue where the `print()` method was firing before the new document window loaded the QR code content.
- Document waits to fire the `focus()` and `print()` methods until after document is fully loaded using `onload()`
- Fix the unit test to check for `print()` and `focus()` after the `onload()` event.
=> BRS-323: Fix print screen appearing before qr img loads in doc

src/app/registration/facility-select/facility-select.component.ts
Relates to #368 
Merging this in now that the hold pass timer stuff is in. Logic shouldnt affect hold pass. 
https://github.com/bcgov/parks-reso-public/issues/368
This error only occurs in the front end and is just a misrepresentation of the actual number of passes available. It only happens when you look ahead at a future date that has no bookings for it yet - the front end assumes that the max number of trail passes one person can book (4) is available if no reservation object exists.
It will also only occur if the total number of base passes allotted to a trail facility is less than 4, which likely will never occur.
This error does not occur for the current date.
This has been fixed by adding a clause where the front end always shows the minimum of 3 possible pass availability values: …
=> PDR-368 fixing facilities showing more passes than available

src/app/registration/contact-form/contact-form.component.html
Hello,
Hope you're doing well.
As it was requested in issue https://github.com/bcgov/parks-reso-public/issues/425, I have updated the spelling of "received" correctly.
Additionally, I have also signed the commit by referring this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and verified using the following command too:
`git log --show-signature`
If at all there's anything else required from my end, then do let me know.
Sincere apologies for my mistakes if you find any.
Thanks and Regards,
Mohit Kambli
=> Fix #425 : DUP Spelling error in message 'New - text message reminders with cancellation links...'

src/app/parks-list/parks-list.component.ts
Ticket: [BRS-449](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=78781413)
Notes: 
* During QA it was discovered if a park was "Closed" and had a "Special Closure" it would be considered a closed park not a special closure. 
* Changed the order for which its closed/specialClosure is decided to match expected behavior.
=> BRS-449: Reorder Parks on DUP homepage

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts, src/app/shared/components/important-booking-info/important-booking-info.component.html
Ticket: [BRS424](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70969356&issue=bcgov%7Cparks-reso-public%7C424)
Notes: 
- This PR is for changing work done in [PR461](https://github.com/bcgov/parks-reso-public/pull/461)
- Front end will store system time from api on page load
- Will then use that time when determining maximum number of days available for booking. 
- All passes will open at 7am two days prior
- Remove alerts from displaying with facility, instead show that information within the Important Booking Information
=> BRS: 424 - Booking Passes prior to 7am

src/app/shared/utils/constants.ts
Ticket: [472](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=86258151&issue=bcgov%7Cparks-reso-public%7C472)
Notes: Changing the front end time for PM passes to reflect the end of daylight savings
=> BRS-472: Change default PM opening hour to 12

src/app/registration/success/facilityConfirmation/diamondHead/diamondHeadConfirmation.component.html, src/app/registration/success/facilityConfirmation/garibaldi/rubbleCreek/rubbleCreekConfirmation.component.html
Ticket: [BRS-459](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=80444271&issue=bcgov%7Cparks-reso-public%7C459)
Notes: 
* Changed the font awesome "droplet" to "glass-water" as requested by BC Parks content team.
* Ticket has requested specified width and height which we have talked about previously as a team. It was decided to use XL sizes for our font awesome icons as they were close to what was requested, and will scale according to our font size.
* Droplet was being used in RubbleCreek and DiamondHead both have been updated.
=> BRS-459: Change Water-Droplet Icon to Drinking-Glass

src/app/registration/facility-select/facility-select.component.spec.ts, src/app/shared/utils/constants.ts
Ticket: [405](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=107867296&issue=bcgov%7Cparks-reso-admin%7C405)
Notes: Adjusting the opening hour to reflect the summer hours of DUP program. Similar to end of summer season done in Commit [7067140](https://github.com/bcgov/parks-reso-public/commit/706714040ae85b51332ac09fa8cec3d82523aba1)
=> BRS-405: Change PM opening hour to 1pm
