bcgov/parks-reso-public

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.html, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.scss, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.spec.ts, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.ts, src/app/pass-lookup/pass-lookup.component.html, src/app/pass-lookup/pass-lookup.component.scss, src/app/pass-lookup/pass-lookup.component.spec.ts, src/app/pass-lookup/pass-lookup.component.ts, src/app/pass-lookup/pass-lookup.module.ts, src/app/registration/success/success.component.html, src/app/shared/components/registration-details/registration-details.component.html, src/app/shared/components/registration-details/registration-details.component.spec.ts, src/app/shared/components/registration-details/registration-details.component.ts, src/app/shared/shared.module.ts, src/assets/base/base.scss
navigate to '/pass-lookup' to view
TODO: link in header to reach this page + implement confirmation email
=> added cancellation page

src/app/home/home.component.ts, src/app/models/pass.ts, src/app/services/api.service.ts, src/app/services/pass.service.ts
=> Setting up post pass

src/app/pass-lookup/pass-lookup.component.html, src/app/pass-lookup/pass-lookup.component.ts, src/app/registration/contact-form/contact-form.component.html, src/app/shared/components/alert/alert.component.html
=> changing cancel page flow

src/app/footer/footer.component.scss, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/pass-lookup/pass-lookup.component.ts, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts, src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts, src/app/registration/failure/failure.component.html, src/app/registration/failure/failure.component.spec.ts, src/app/registration/failure/failure.component.ts, src/app/registration/registration.component.html, src/app/registration/registration.component.ts, src/app/registration/registration.module.ts, src/app/services/pass.service.ts
Mobile bugs fixed:
* pages now scroll to top on navigation
* Added redirect page when reservation submission fails to improve UX
* Enforced character restrictions in phone number field
* Removed white space under footer in mobile view
* Fixed banner title spacing
=> FLCN-163 various bug fixes

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/pr.yaml, .github/workflows/tf-plan.yaml, terraform/dev/terragrunt.hcl, terraform/prod/terragrunt.hcl, terraform/terragrunt.hcl, terraform/test/terragrunt.hcl
[FLCN-135](https://bcmines.atlassian.net/browse/FLCN-135)
=> FLCN-135: add github actions and terragrunt config files for cloud pipeline

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
- variables have already been set it github env (except prod)
=> update sed to allow api url to be pulled for gh action environment

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-165
https://bcmines.atlassian.net/browse/BRS-165
Update high/medium/low:
- if there are 75% or more left = High
- if there are 25-75% left = moderate
- if there are less than 25% left = low
There will also be an API PR (I think) to stop accepting passes over the max number of available.
=> BRS-165: update values for low/medium availability

src/app/registration/facility-select/facility-select.component.html, src/app/registration/park-details/park-details.component.html
BRS-93
https://bcmines.atlassian.net/browse/BRS-93
Content updates to DUP parks page.
=> BRS-93: parks page content updates

src/app/shared/components/registration-details/registration-details.component.html
BRS-95
https://bcmines.atlassian.net/browse/BRS-95
UI updates to success page.
=> BRS-95: updates to success page

src/app/home/home.component.html
BRS-157
https://bcmines.atlassian.net/browse/BRS-157
Updated wording.
=> BRS-157: update wording on home component

src/app/registration/success/success.component.html
BRS-95
https://bcmines.atlassian.net/browse/BRS-95
Fixing typo.
=> BRS-95 typo

src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-165
https://bcmines.atlassian.net/browse/BRS-165
Now checks for existing reservations in ISO format, YYYY-MM-DD.
Looks like we switched format slightly for consistency in https://github.com/bcgov/parks-reso-api/pull/30.
=> BRS-165: update date format to match API

src/app/registration/park-details/park-details.component.html
BRS-187
https://bcmines.atlassian.net/browse/BRS-187
Parks description now uses innerHTML.
=> BRS-187: Enabled innerhtml for park descriptions.

.github/pull_request_template.md, src/app/card/card.component.ts, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.spec.ts, src/app/registration/contact-form/contact-form.component.ts, src/app/registration/facility-select/facility-select.component.html, src/env.js, terraform/src/cloudfront.tf
BRS-94 
https://bcparksdigital.atlassian.net/browse/BRS-94 
- Updated contact info page contents
- Updated assets Cloudfront origin root to be `/assets` instead of `/assets/images`.  It didn't make sense to store non-images in the `/images` directory
=> BRS-94 Update contact info page

.browserslistrc, angular.json, package.json, src/index.html, src/snowplow.js
BRS-147
https://bcparksdigital.atlassian.net/browse/BRS-147
Set up site metrics for Parking Pass site.
=> BRS-147: Adding snowplow

package.json, yarn.lock
=> NOBUG: Fixing font issue

src/app/registration/success/success.component.html
BRS-95
https://bcparksdigital.atlassian.net/browse/BRS-95
Updating email address to be parkinfo@gov.bc.ca
=> BRS-95 updating contact email

src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts, src/env.js, src/env.js.template
BRS-148
https://bcparksdigital.atlassian.net/browse/BRS-148
Use facility booking start time and days, with fallback to the default.
Also fix UTC offset in date math causing tests to fail after midnight
UTC.
=> BRS-148: use facility booking start time and days if set

src/app/registration/contact-form/contact-form.component.html
BRS-94 
https://bcparksdigital.atlassian.net/browse/BRS-94 
Fix checkbox alignment on small screens where the label appears on next line
=> BRS-94 Fix checkbox alignment on small screens

src/app/home/home.component.html
BRS-206
https://bcparksdigital.atlassian.net/browse/BRS-206
Content updates to front page
=> BRS-206 content updates to front page

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.scss, src/app/registration/facility-select/facility-select.component.ts
BRS-204
https://bcparksdigital.atlassian.net/browse/BRS-204
Adjusting the AM/PM/DAY selection cards to match each other's heights at any screen size. Additionally, changing the card radio inputs to work as radio inputs for accessibility.
=> BRS-204 responsive booking time area

src/app/home/home.component.html
BRS-206
https://bcparksdigital.atlassian.net/browse/BRS-206
Content requiring update was not clear in original ticket. This is the proper update.
=> BRS-206-2 content updates 

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.scss
BRS-204
https://bcparksdigital.atlassian.net/browse/BRS-204
With the last change for BRS-204, actual radio buttons were inserted into the AM/PM/DAY cards. This changed the styling of the radio buttons and made it slightly confusing whether a button was active or not. This change alters the radio button styling slightly to make it match the prior styling. Descriptive text of arrival/departure times was also moved out of the card header and into the card body to ensure card headers remain the same size on all screens.
=> BRS-204 changing card styling

src/app/card/card.component.html, src/app/card/card.component.scss, src/app/footer/footer.component.html, src/app/home/home.component.html, src/app/parks-list/parks-table-row/parks-table-row.component.html
BRS-237
https://bcparksdigital.atlassian.net/browse/BRS-237
Cleaning up the reskin on the front page. Components are now responsive and the tab order follows the page. Park card formats updated. Screen reader reads out which park the booking button is for.
=> BRS-237 front page responsiveness

src/app/card/card.component.html, src/app/card/card.component.scss, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/registration/facility-select/facility-select.component.html, src/app/registration/guidelines/guidelines.component.html, src/app/registration/guidelines/guidelines.component.scss, src/app/registration/park-details/park-details.component.scss, src/app/registration/registration.component.html, src/app/registration/registration.component.scss
BRS-237
https://bcparksdigital.atlassian.net/browse/BRS-237
This change cleans up mobile view on the homepage and facility page.
=> BRS-237 clean up facility page

src/app/app.component.scss, src/app/breadcrumb/breadcrumb.component.scss, src/app/card/card.component.scss, src/app/header/header.component.scss, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.html, src/app/registration/facility-select/facility-select.component.scss, src/app/shared/components/registration-details/registration-details.component.html, src/assets/base/base.scss, src/assets/themes/default.scss
=> NOBUG: Cleaning up scss

src/app/home/home.component.html, src/app/pass-lookup/pass-lookup.component.html, src/app/pass-lookup/pass-lookup.component.ts, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss, src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.scss, src/app/registration/guidelines/guidelines.component.html, src/assets/base/base.scss
BRS-237
https://bcparksdigital.atlassian.net/browse/BRS-237
Cleaning up the contact information collection page and the cancellation page for the application reskin. Changes contained:
* Contact information page now mobile friendly w/reskin
* Cancellation page now mobile friendly w/reskin
* Re-added the fields that appear on the cancellation page during cancellation flow - these many need up-to-date designs.
* Reskinned visitation time cards to include a `disabled` style
* Changed "<- Home" button to not fill width on small screen size to match designs
* Minor respacing/formatting/typos
=> BRS-237 cleaning up contact, cancellation pages

src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts, src/app/card/card.component.html, src/app/card/card.component.scss, src/app/footer/footer.component.html, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/tips/tips.component.html, src/app/tips/tips.component.scss, src/app/tips/tips.component.spec.ts, src/app/tips/tips.component.ts
Updating home page responsiveness
=> NOBUG: home page responsiveness

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts, src/app/registration/guidelines/guidelines.component.html, src/app/registration/guidelines/guidelines.component.scss, src/app/registration/registration.component.html
BRS-236
https://bcparksdigital.atlassian.net/browse/BRS-236
Allowing only one pass to be booked when pass type is parking. This will also be enforced in a change in the api.
=> BRS-236: If parking pass selected, only allow one pass to be reserved.

src/app/footer/footer.component.html, src/app/header/header.component.html, src/app/registration/registration.component.html
Adding alt labels to header and footer
=> NOBUG: Adding alt labels to header and footer

src/app/registration/registration.component.html, src/app/registration/success/success.component.html, src/app/registration/success/success.component.scss, src/app/registration/success/success.component.ts, src/app/shared/components/registration-details/registration-details.component.html, src/app/shared/components/registration-details/registration-details.component.scss, src/app/shared/components/registration-details/registration-details.component.ts, src/assets/base/base.scss
BRS-237, BRS-207
https://bcparksdigital.atlassian.net/browse/BRS-237
Reskinning success page to match Figma designs. Also adding park name to the success page details (BRS-207)
=> BRS-237 reskinning success page

src/app/registration/failure/failure.component.html, src/app/registration/failure/failure.component.scss
=> NOBUG: Updating failure page

src/app/captcha/captcha.component.html, src/app/card/card.component.html, src/app/card/card.component.scss, src/app/header/header.component.scss, src/app/not-found/not-found.component.html, src/app/registration/contact-form/contact-form.component.html, src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.scss, src/app/registration/success/success.component.html, src/app/shared/components/date-picker/date-picker.component.html, src/app/shared/components/date-picker/date-picker.component.ts, src/app/shared/components/registration-details/registration-details.component.html, src/assets/base/base.scss, src/assets/themes/default.scss
Improving contrast. Adding missing labels.
=> NOBUG: Improving contrast. Adding missing labels.

src/app/card/card.component.scss, src/app/home/home.component.html, src/app/registration/park-details/park-details.component.html, src/app/registration/park-details/park-details.component.scss, src/app/registration/park-details/park-details.component.ts, src/app/tips/tips.component.html
BRS-240, BRS-239
https://bcparksdigital.atlassian.net/browse/BRS-240
This change incorporates the final content updates to the homepage. It also adds a button on the park details page that links to the parking map for the park, if the link exists.
=> BRS-239/-240, home page COPY & map button

src/app/registration/facility-select/facility-select.component.html, src/app/registration/guidelines/guidelines.component.html, src/app/registration/park-details/park-details.component.html
BRS-241
https://bcparksdigital.atlassian.net/browse/BRS-241
This change incorporates the final content updates for the book a pass page before the Dec. 15th release.
* Book a pass page content updated
* If site admins provide a link to the bcparks.ca page for a park, a link appears on the page saying "For more information about <park>, visit the BC Parks page here".
* "Number of Passes Required" field no longer appears when `passType` = 'Parking'. It is replaced with a blurb of text explaining 1 pass per vehicle regulations.
=> BRS-241 book a pass COPY

src/app/home/home.component.html
BRS-240
https://bcparksdigital.atlassian.net/browse/BRS-240
Minor homepage content updates
=> minor homepage content updates

src/assets/base/base.scss
important info header colour set to black
=> NOBUG: important info header colour set to black

src/app/registration/contact-form/contact-form.component.html
BRS-242
https://bcparksdigital.atlassian.net/browse/BRS-242
This change incorporates the finalized content for the contact information page.
=> BRS-242 contact page content update

src/app/registration/success/success.component.html, src/app/shared/components/registration-details/registration-details.component.html
BRS-243
https://bcparksdigital.atlassian.net/browse/BRS-243
This change incorporates the finalized success page content.
=> BRS-243 finalizing success page content

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts
BRS-258
https://bcparksdigital.atlassian.net/browse/BRS-258
Fixing captcha form
=> BRS-258: Fixing captcha form

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts
BRS-259
https://bcparksdigital.atlassian.net/browse/BRS-259
Fixing booking select case with 1 pass remaining.
=> BRS-259: Fixing booking select case with 1 pass remaining.

src/app/footer/footer.component.html, src/app/registration/facility-select/facility-select.component.html
Updating footer. Cleaning up booking times ui.
=> BRS-260: Clean up

src/app/captcha/captcha.component.html, src/app/captcha/captcha.component.scss, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/pass-lookup/pass-lookup.component.html, src/app/pass-lookup/pass-lookup.component.scss, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss, src/app/registration/facility-select/facility-select.component.html, src/app/registration/registration.component.html, src/app/registration/registration.component.scss, src/app/registration/success/success.component.html, src/app/shared/components/registration-details/registration-details.component.html
BRS-257
https://bcparksdigital.atlassian.net/browse/BRS-257
Post demo cleanup.
=> BRS-257: post demo cleanup

src/app/home/home.component.html
=> NOBUG: Bolding important sentance.

src/app/registration/contact-form/contact-form.component.html
NOBUG: license to uppercase
This ticket forces the license input field to uppercase.
=> NOBUG: force license plate to uppercase in front end

src/app/captcha/captcha.component.html, src/app/captcha/captcha.component.scss, src/app/pass-lookup/pass-lookup.component.html, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss, src/app/registration/park-details/park-details.component.html
=> NOBUG: Improving captcha for mobile

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-266
https://bcparksdigital.atlassian.net/browse/BRS-266
disable pass type selection if available is 0
=> BRS-266: disable pass type selection if available is 0

src/app/pass-lookup/pass-lookup.component.ts, src/app/shared/components/alert/alert-object.ts, src/app/shared/components/alert/alert.component.html
BRS-265
https://bcparksdigital.atlassian.net/browse/BRS-265
Updating cancel message in front end - following submission that sends timed cancel email, an info alert pops up on the screen .
=> BRS-265 Update cancel message

terraform/src/cloudfront.tf
NOBUG
Removes PW protection on public.
=> NOBUG: Remove pw protection

src/app/registration/success/success.component.html
BRS-268
https://bcparksdigital.atlassian.net/browse/BRS-268
This change formats the success page to make screenshots on mobile contain more relevant information. Reservation number is removed and 'Print' button is moved to below the information box.
=> BRS-268 success page screenshot format

package.json
Removes "Angular is running in development mode. Call enableProdMode() to enable production mode." console notice, and improves performance.
=> NOBUG: build in production mode

src/app/registration/facilities-resolver.service.ts, src/app/registration/registration.component.ts
BRS-267
https://bcparksdigital.atlassian.net/browse/BRS-267
Refreshing cache of facility when error occurs.
=> BRS-267: refreshing cache of facility when error occurs

src/app/app.module.ts, src/app/home/home.component.html, src/app/registration/facility-select/facility-select.component.html, src/app/registration/registration.module.ts, src/app/shared/components/important-booking-info/important-booking-info.component.html, src/app/shared/components/important-booking-info/important-booking-info.component.spec.ts, src/app/shared/components/important-booking-info/important-booking-info.component.ts, src/app/shared/components/important-booking-info/important-booking-info.module.ts
BRS-283
https://bcparksdigital.atlassian.net/browse/BRS-283
Updating important booking info.
=> BRS-283: Updating important booking info

src/app/shared/components/important-booking-info/important-booking-info.component.html
BRS-283
https://bcparksdigital.atlassian.net/browse/BRS-283
Fixing typo for BRS-283.
=> BRS-283: Typo

src/app/registration/contact-form/contact-form.component.html
BRS-326 
https://bcparksdigital.atlassian.net/browse/BRS-326 
Updated public collection notice text and confirmation feedback email
=> BRS-326 Update collection notice and confirmation feedback email

src/app/registration/contact-form/contact-form.component.html
BRS-326 
https://bcparksdigital.atlassian.net/browse/BRS-326 
Fix extra space before period in collection notice text.
=> BRS-326 Fix extra space before period in collection notice text

src/app/home/home.component.html
BRS-611
https://bcparksdigital.atlassian.net/browse/BRS-611
Unhiding parks list to allow for testing.
=> BRS-611 unhide parks list

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-570
https://bcparksdigital.atlassian.net/browse/BRS-570
Re-ordered the day use pass entry form so Visit Date is selected first, then facility.  
The date picker and facility selector now behave independently, such that:
1. when a users has a date picked and toggles between different facilities the date remains
2. when a users has a facility selected and toggles between different dates the facility remains
=> BRS-570: Re-order public DUP booking fields

src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.html, src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.ts, src/app/pass-lookup/pass-lookup.component.ts
BRS-296
https://bcparksdigital.atlassian.net/browse/BRS-296
Adding pass date and type display to intermediate cancellation page. 
https://github.com/bcgov/parks-reso-api/pull/93 should be approved before testing this PR.
=> BRS-296-2: showing date in more places

src/app/models/pass.ts, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts, src/app/registration/registration-details/registration-details.component.html, src/app/registration/registration.component.ts, src/app/services/pass.service.ts
BRS-620
https://bcparksdigital.atlassian.net/browse/BRS-620
This removes the license plate logic, validators, and visuals from DUP public site.  Required back-end PR is located here:  https://github.com/bcgov/parks-reso-api/pull/99
=> BRS-620: Remove License Plate field from DUP

src/app/registration/contact-form/contact-form.component.html, src/app/registration/facility-select/facility-select.component.html
BRS-621
https://bcparksdigital.atlassian.net/browse/BRS-621
This ticket is to update the text shown under booking time and remove the check boxes from the last page in the process.
=> BRS-621: Times changed for booking, winter related text hidden

src/app/registration/contact-form/contact-form.component.html, src/app/registration/facility-select/facility-select.component.html
BRS-621
https://bcparksdigital.atlassian.net/browse/BRS-621
This is a description.
=> BRS-621: excluded winter checkboxes from submission conditions

src/app/home/home.component.html
BRS-563
https://bcparksdigital.atlassian.net/browse/BRS-563
This is a description.
=> BRS-563: small update to textbox on home page

src/app/registration/guidelines/guidelines.component.html, src/app/shared/components/important-booking-info/important-booking-info.component.html
BRS-563
https://bcparksdigital.atlassian.net/browse/BRS-563
another small update to text
=> BRS-563: another small update to text

package.json, yarn.lock
BRS-661
https://bcparksdigital.atlassian.net/browse/BRS-661
Upgrading cli to latest LTS. Our version of angular-cli was using json-schema@0,2,3 which has a vulnerability.
=> BRS-661: upgrading cli to latest LTS.

src/app/footer/footer.component.html
BRS-679
https://bcparksdigital.atlassian.net/browse/BRS-679
Updating email subject line.
=> BRS-679-2 updating email subject

terraform/src/cloudfront.tf
BRS-686
https://bcparksdigital.atlassian.net/browse/BRS-686
BRS-686: Enable Blacklist for restricted countries.
=> BRS-686: Enable Blacklist for restricted countries.

src/app/home/home.component.html, src/app/shared/components/important-booking-info/important-booking-info.component.html
BRS-682
https://bcparksdigital.atlassian.net/browse/BRS-682
Change "day use pass" to "day-use pass" and "first-come first-serve" to "first come, first served"
=> Fix 'day-use' and 'first come, first served' text

src/app/registration/contact-form/contact-form.component.html, src/app/registration/registration-details/registration-details.component.html
BRS-695
https://bcparksdigital.atlassian.net/browse/BRS-695
- Show the pass count on the success screen when booking a day-use pass (parking and trail)
- Update the label on the confirmation and the success screen, so there is a different label for trail passes and parking passes
=> BRS-695: Display pass count on success screen when booking a pass

src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts, src/app/services/api.service.ts, src/app/services/facility.service.ts
BRS-720: api call added to get reservations, formatting
BRS-720
https://bcparksdigital.atlassian.net/browse/BRS-720
Update UI to use our new reservation object instead of the reservation object found in facility objects.
=> BRS-720: pass booking logic updated to match new data model 

src/app/registration/facility-select/facility-select.component.ts
BRS-739
https://bcparksdigital.atlassian.net/browse/BRS-739
Fix ability to book AM passes even though AM has already passed.
=> BRS-739: fixed bug causing AM card to be active after booking window

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss, src/app/registration/contact-form/contact-form.component.ts, src/assets/themes/default.scss
BRS-733: code updated to fix deprecated group issue
BRS-733
https://bcparksdigital.atlassian.net/browse/BRS-733
Add second email field to reduce number of wrong email addresses being entered by public
=> BRS-733: email check working with paste disabled

src/app/shared/components/important-booking-info/important-booking-info.component.html
BRS-753
https://bcparksdigital.atlassian.net/browse/BRS-753
remove the last bullet in the DUP yellow text box so that it better aligns with comms
=> BRS-753: Removed last bullet point in yellow box

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-787
https://bcparksdigital.atlassian.net/browse/BRS-787
FE portion of BRS-787 that goes along with weekday specific booking changes of BRS-768
=> BRS-787 FE public changes for weekday bookings

src/app/registration/facility-select/facility-select.component.html
Poss fix for invalid pass type.
=> NOBUG: Poss fix for invalid pass type.

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts
NOBUG
Changing a getter to a function call to eliminate possible bug sources.
=> NOBUG changing booking day get to function

src/env.js.template
BRS-808
https://bcparksdigital.atlassian.net/browse/BRS-808
This fixes the string being replaced by the github action.
=> BRS-808: Fix for strings in github action

src/app/shared/services/config.service.ts
BRS-808
https://bcparksdigital.atlassian.net/browse/BRS-808
This ensures the build hash sticks to the configuration.
=> BRS-808: Update hash

src/app/card/card.component.html
BRS-797
https://bcparksdigital.atlassian.net/browse/BRS-797
Minor wording change: 'open/closed' => 'passes required/passes not required" at the park level
=> BRS-797 changing open/closed to passes required/not required at park level

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-pr.yaml
Reverts bcgov/parks-reso-public#183 (not required)
=> Revert "NOBUG - upgrading GH Actions to Node16"

src/app/tips/tips.component.html
BRS-863
https://bcparksdigital.atlassian.net/browse/BRS-863
=> BRS-863: update language for 'here' links

src/app/registration/contact-form/contact-form.component.html
BRS-566
https://bcparksdigital.atlassian.net/browse/BRS-566
This is a small portion of BRS-566 (email reminder service) that updates front-end text.
=> BRS-566 update contact email text

package.json, src/app/registration/park-details/park-details.component.ts
BRS-900
https://bcparksdigital.atlassian.net/browse/BRS-900
Adding alternate photo for seymour.
=> BRS-900: Adding alternate photo for Seymour

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts
BRS-896
https://bcparksdigital.atlassian.net/browse/BRS-896
Added detection for winterWarning flag from api. Added extra UI checks before reso submission.
=> Add checks for winter waiver

angular.json, karma.conf.js
This is adds code coverage report to the cli.
=> NOBUG: Adding CC reporting to cli.

src/app/app.component.spec.ts, src/app/services/api.service.ts, src/app/services/facility.service.ts, src/app/services/logger.service.ts, src/app/services/park.service.ts, src/app/services/pass.service.ts, src/app/shared/services/config.service.spec.ts, src/app/shared/services/config.service.ts, src/env.js
BRS-948
https://bcparksdigital.atlassian.net/browse/BRS-948
This is improves the logging levels in DUP Public.
=> BRS-948: Improve Logging levels in the A&R and DUP front-ends

src/app/card/card.component.spec.ts
NOBUG
This gets 💯  code coverage of the card component.
=> NOBUG: UT coverage for card component.

karma.conf.js
NOBUG
Duplicates the application console logs into the karma web console logs so that you can view logs in the same window.
=> NOBUG: adding application console log to karma console

src/app/breadcrumb/breadcrumb.component.spec.ts, src/app/breadcrumb/breadcrumb.component.ts
This improves code coverage tests.
=> NOBUG: Adding cc to ut's.

src/app/registration/registration.component.ts
BRS-825
https://bcparksdigital.atlassian.net/browse/BRS-825
Accessibility of this alert has also been fixed.
=> BRS-825: fixing alert behaviour

src/app/pass-lookup/pass-lookup-form/pass-lookup-form.component.html
BRS-826
https://bcparksdigital.atlassian.net/browse/BRS-826
Missing form labels on Cancel a Reservation page
=> BRS-826: Fixed missing labels on cancel form

src/app/card/card.component.html, src/app/card/card.component.scss, src/app/card/card.component.ts, src/app/registration/park-details/park-details.component.ts
BRS-964
https://bcparksdigital.atlassian.net/browse/BRS-964
Updating cards to look for webp.
=> BRS-964: Updating cards to look for webp

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts, src/app/shared/utils/constants.ts
BRS-829
https://bcparksdigital.atlassian.net/browse/BRS-829
Updating email validation.
=> BRS-829: Updating email validation

src/app/registration/facility-select/facility-select.component.html
BRS-1007
https://bcparksdigital.atlassian.net/browse/BRS-1007
Update the closing time of AM slot and opening time of PM slot. (Change both from 1pm to 12pm)
=> BRS-1007: Update AM/PM times

src/app/models/pass.ts, src/app/registration/registration.component.ts, src/app/services/pass.service.ts
BRS-794
https://bcparksdigital.atlassian.net/browse/BRS-794
DUP Public front end changes for BRS-794. Rollout of this change must be done in a specific order:
1. Run create.js and delete.js from https://github.com/bcgov/parks-reso-api/pull/210 in that order in the appropriate DynamoDB env. This will create new instances of objects using the new parks sk and will remove all references to old instances.
2. Deploy and test [API](https://github.com/bcgov/parks-reso-api/pull/222)
3. Deploy and test front ends ([Admin](https://github.com/bcgov/parks-reso-admin/pull/215) and Public (this change))
4. Update S3 references to park images (now ORCS instead of park name).
=> BRS-794: changes to public FE

src/app/app.module.ts, src/app/registration/success/success.component.html, src/app/registration/success/success.component.spec.ts
BRS-1025
https://bcparksdigital.atlassian.net/browse/BRS-1025
Adding fidelity to the QR code quality.  Also added 💯% CC.
=> BRS-1025: Adding fidelity to the QR code quality.  Also added 100% CC.  Cleanup.

.github/workflows/deploy-dev.yaml, .github/workflows/on-pr.yaml, .github/workflows/zap-scan.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Revising dev workflow. Updating Pr and zap workflows.
=> BRS-1051: Revising dev workflow. Updating Pr and zap workflows

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-pr.yaml
BRS-1051
https://bcparksdigital.atlassian.net/browse/BRS-1051
Changing cache id.
=> BRS-1051: Changing cache id

src/app/registration/success/success.component.html
BRS-1084
https://bcparksdigital.atlassian.net/browse/BRS-1084
Adding QR Code related text to confirmation page.
=> BRS-1084: Adding QR Code related text to confirmation page

src/app/registration/success/success.component.html
BRS-1085
https://bcparksdigital.atlassian.net/browse/BRS-1085
Removed the QR code trial text from confirmation page.
=> BRS-1085: Removed trial text from DUP confirmation page

src/app/tips/tips.component.html
BRS-994
https://bcparksdigital.atlassian.net/browse/BRS-994
=> BRS-994: Updating Hyperlink for Public page

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
BRS-1099
https://bcparksdigital.atlassian.net/browse/BRS-1099
Change PM booking slot time from 12pm -> 1pm. This is paired with a backend change as part of BRS-1099
=> BRS-1099: Update PM slot time from 12pm to 1pm in component

package.json, yarn.lock
BRS-1139
https://bcparksdigital.atlassian.net/browse/BRS-123
This updates a number of packages.
=> BRS-1139: Various package updates.

package.json, src/app/parks-list/parks-list.component.ts, yarn.lock
BRS-1148
https://bcparksdigital.atlassian.net/browse/BRS-1148
Updating order of park list.
=> BRS-1148: Updating order of park list

src/app/parks-list/parks-list.component.ts
BRS-1148
https://bcparksdigital.atlassian.net/browse/BRS-1148
Implementing alpha sort to parks list.
=> BRS-1148: Implementing alpha sort to parks list

CODEOFCONDUCT.md, LICENSE.md, README.md
BRS-1204
https://bcparksdigital.atlassian.net/browse/BRS-123
I hope I did this right, just checking to see if I could do the PR....
This is a description.
=> BRS-1024: Changes to README.md

README.md
Cam and I squashed my other commits and ripped this final one in. Just some technical updates for local dev.
=> BRS-1204 additional changes

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, README.md
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Documentation and updated env setting.
=> BRS-1152: Documentation and updated env setting.

.github/workflows/deploy-test.yaml
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Remove lock.
=> BRS-1152: Remove lock.

.github/workflows/deploy-dev.yaml
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Remove temp lockfile unlocker.
=> BRS-1152: Remove temp lockfile unlocker.

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.spec.ts, src/app/shared/components/captcha/captcha-data.service.ts, src/app/shared/components/captcha/captcha.component.ts
BRS-1251
https://bcparksdigital.atlassian.net/browse/BRS-1251
Updating captcha to prevent replay attack.
This code requires https://github.com/bcgov/parks-reso-api/pull/282
=> BRS-1251: Updating captcha to prevent replay attack

src/app/home/home.component.html, src/app/registration/facility-select/facility-select.component.html
BRS-1262
https://bcparksdigital.atlassian.net/browse/BRS-1262
=> BRS-1262 vehicle capacity to 12

src/app/registration/contact-form/contact-form.component.html, src/app/shared/components/captcha/captcha-data.service.ts, src/app/shared/components/captcha/captcha.component.spec.ts, src/app/shared/components/captcha/captcha.component.ts
This updates the negotiated logic.
=> NOBUG: Updating logic c/o @cameronpettit

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml, .github/workflows/on-pr.yaml, src/env.js
NOBUG
https://bcparksdigital.atlassian.net/browse/NOBUG
Updating to node 18. Fixing missing build hash.
=> NOBUG: Updating to node 18. Fixing missing build hash

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
NOBUG
Updating aws actions for creds.
=> NOBUG: Updating aws actions for creds

src/app/services/api.service.ts
This adds version header information to header requests.  Back-end PR: https://github.com/bcgov/parks-reso-api/pull/299
=> NOBUG: Adding version header information to request.

src/app/registration/park-details/park-details.component.html, src/app/registration/park-details/park-details.component.spec.ts, src/app/registration/park-details/park-details.component.ts
BRS-267
Ticket #267 
[Links to API PR - https://github.com/bcgov/parks-reso-api/pull/298](https://github.com/bcgov/parks-reso-api/pull/298)
[Links to ADMIN PR - https://github.com/bcgov/parks-reso-admin/pull/304](https://github.com/bcgov/parks-reso-admin/pull/304)
https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=39881272
* Added conditional logic to display video link. Added tests to support Park video and map being displayed
=> Brs 267: Add safety video to PUBLIC

src/app/registration/facility-select/facility-select.component.ts
#280 
[https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42235243](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=42235243)
Adding missing piece to prevent users from booking am passes after 12:00
=> BRS-280: Change AM expiry from 13:00 to 12:00

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.spec.ts, src/app/registration/contact-form/contact-form.component.ts, src/app/registration/registration.module.ts, src/app/shared/components/phone-number-formater/phoneFormat.ts, src/app/shared/utils/constants.ts
BRS-288
[BRS-288: Opt in to SMS reminder in DUP Public](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=43920615)
- Update form to include checkbox to opt in to SMS reminder
- Update form to include field for phone number
- Logic to handle phone number on submission (include if opted in / validate if opted in / remove hyphens upon submit)
- Include new directive to format phone numbers and validate information provided
- Tests to ensure phone number length is limited and clear phone number input upon opting out
- Update regex validation on phone number field to include hyphens
=> BRS-288: Add SMS Messaging

src/app/shared/components/phone-number-formater/phoneFormat.ts
BRS-298
[BRS-298](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=46259414)
Removing the ability to paste into the number field.
=> BRS-298: Prevent users from pasting into phone number field

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/faq/faq.component.html, src/app/faq/faq.component.ts, src/app/faq/faq.module.ts, src/app/footer/footer.component.html, src/app/registration/registration.component.html, src/app/registration/registration.component.ts, src/app/services/faq.service.ts
BRS-289
[BRS-289](
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=43920696)
Also Includes: 
[BRS-302](
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055380)
Implements the FAQ page for DUP Public
Updates the Links previously used to contact support with Link to new FAQ page.
Template for FAQ includes static information for contacting support along with admin set FAQ
=> BRS:289 - Create FAQ page for DUP-Public

src/app/registration/registration.component.html
BRS-302
[BRS-302](
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055380)
This adds the link to FAQ too error page which appears when passes are sold out during registration process.
=> BRS-302: Adding FAQ link to another error page

src/app/registration/registration.component.html
[BRS-302](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055380)
[BRS-302](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055380)
Removing contact email from error page (Fail to retrieve park list). 
The contact email is found on the FAQ page.
=> BRS-302:Removing contact email from error page

src/app/services/faq.service.ts
[BRS-289](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=43920696)
[BRS-289](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=43920696)
Changing service to point at proper endpoint.
=> BRS-289: Fix - Changing service to proper endpoint

src/app/faq/faq.component.html, src/app/faq/faq.component.scss, src/app/faq/faq.component.ts
BRS-318
[BRS-318](https://github.com/bcgov/parks-reso-public/issues/318)
Added Home button to FAQ page to navigate to DUP home when clicked.
=> BRS-318: Adding back button to FAQ page

src/app/faq/faq.component.html, src/app/faq/faq.component.ts
BRS-317
https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=51223903
- On page load show a spinner while waiting on response from api
- Upon response stop showing spinner
- If no response or error show TOAST message.
=> BRS-317: Add Loading Spinner 

src/app/card/card.component.html, src/app/card/card.component.scss, src/app/card/card.component.ts
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57407980)
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57407980)
Update DUP-Public facility cards to show special closures and special closure text.
=> BRS-326:Special Closures displayed on DUP-Public

src/app/header/header.component.html
[BRS-347](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=59471877)
[BRS-347](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=59471877)
Update the BCParks logo link to return to DUP homepage
=> BRS-347:Change BCParks logo to return to homepage of DUP

src/app/card/card.component.html
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57407980)
[BRS-326](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57407980)
Text change as requested to match status of other scenarios.
=> BRS-326 FIX: Changing text for limited access no passes

src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.scss, src/app/registration/contact-form/contact-form.component.ts, src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.ts, src/app/registration/registration.component.html, src/app/registration/registration.component.scss, src/app/registration/registration.component.ts, src/assets/base/base.scss
DUP-333
https://github.com/bcgov/parks-reso-public/issues/333
Moving back button as seen in:
https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3975%3A17140&mode=design&t=YbmeWNjWNn9tCaMc-1
https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=3980%3A18613&mode=design&t=YbmeWNjWNn9tCaMc-1
=> DUP-333: Moving back button.

src/app/home/home.component.html, src/app/home/home.component.scss, src/app/shared/components/important-booking-info/important-booking-info.component.html, src/app/tips/tips.component.html
BRS-338
#338
Updating DUP home content to include information about hold pass - following this:
https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B008EAE24-83BE-4F84-B144-F77470B79C29%7D&file=day-use-pass-system-home-v0.1.docx&wdLOR=c1A82600D-B28E-4F56-B44A-A7BBBAD44E48&action=default&mobileredirect=true
Update to Cancel my pass button following as seen in this:
https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4464%3A9887&mode=design&t=g9d631EUDA9crfiG-1
=> BRS-338: Update content on DUP homepage - includes hold pass info

src/app/card/card.component.html
No Ticket - Text change requested from business area
Changing wording for special closure card label
=> No-Ticket:Text change for special closures

src/app/registration/facility-select/facility-select.component.html, src/app/registration/guidelines/guidelines.component.html
BRS-339
#339 
Update text for the Park booking page as outlined in [this document](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7BA34EA26A-4F09-4BAC-B27C-4D3018643484%7D&file=day-use-pass-system-mount-seymour-v0.1.docx&wdLOR=cB7A430E5-82D6-44AF-BC63-A2A1501CD792&action=default&mobileredirect=true).
=> BRS-339: Update text for park booking page

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts, src/app/shared/utils/constants.ts
Relates to [#359](https://github.com/bcgov/parks-reso-public/issues/359)
Updates the PM opening hour to 1300 (1pm)
=> PDR-359 change PM opening hour to 1pm

src/app/home/home.component.html, src/app/shared/components/important-booking-info/important-booking-info.component.html
BRS-338
#338
Remove content in "Important booking information"
Fix to spacing of "Cancel my pass" button on mobile
=> BRS-338 Fix: correct booking info text, fix for mobile spacing

src/app/card/card.component.html
No Ticket
No Ticket
As requested from service area. 
Change color of closed parks from Yellow -> Red
CSS classes unchanged (not removed). Possibility of usage down the road.
=> BRS:Changing color of closed to red

src/app/registration/success/success.component.html, src/app/registration/success/success.component.ts
BRS-341
#341 
Update content on "Success" page as per [this document](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/Doc.aspx?sourcedoc=%7B4ED28D03-2139-4A4E-8987-293F5EC2EF18%7D&file=day-use-pass-system-success-v0.1.docx&wdLOR=c968C8893-A4CA-4CA4-89F5-6127C1F50CDA&action=default&mobileredirect=true).
=> BRS-341: Update content on success page

src/app/pass-lookup/pass-lookup.component.html
BRS-342
#342
Update content on "Cancel a reservation" page as per [this document](https://bcgov.sharepoint.com/:w:/r/teams/031072/_layouts/15/doc2.aspx?sourcedoc=%7BB2E04E68-9C73-45AC-A16D-0FEB62417846%7D&file=day-use-pass-system-pass-lookup-v0.1.docx&wdLOR=cD4BA6755-8B99-4DBC-8D8B-0A3994F5C20E&action=default&mobileredirect=true).
=> BRS-342: Update content on cancel pass page

src/app/registration/contact-form/contact-form.component.html
BRS-340
#340
Fix two typos on the "Contact form" page.
- Remove duplicate punctuation
- Missing comma
=> BRS-340 FIX: Typo fixes for Contact form page

src/app/pass-lookup/pass-lookup.component.html
BRS-342
#342 
Fix a typo on the "Cancel" page.
=> BRS-342: Typo fix for "Cancel" page

src/app/registration/timer/timer.component.html
=> PDR-334-2 sticky timer bar

src/app/faq/faq.component.html
https://github.com/bcgov/parks-reso-public/issues/389
=> DUP-389: text changed to full width

src/app/registration/park-details/park-details.component.html
https://github.com/bcgov/parks-reso-public/issues/388
=> DUP-388: Removed the word 'safety' from video link

src/app/registration/registration.component.ts
=> 395: error message updated

README.md, src/app/registration/contact-form/contact-form.component.html, src/app/registration/contact-form/contact-form.component.ts, src/app/shared/utils/constants.ts
Ticket: 
[421](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70648969)
Description: 
- Created array of facilities that need restricted SMS messaging. 
- Added 'Alouette Lake South Beach Day-Use Parking Lot' to array. 
- Do no render SMS messaging options while facility is present.
- Updated README with CF note for local setup.
=> BRS:421 - Remove SMS Option

src/app/card/card.component.html
BRS: 406
Ticket: 
[406](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=67356521)
Details: 
Text change to card depending on availability
=> BRS: 406: Text change for pass required card

src/app/parks-list/parks-list.component.ts, src/app/registration/success/facilityConfirmation/garibaldi/rubbleCreek/rubbleCreekConfirmation.component.html, src/app/tips/tips.component.html
Tickets:
[419](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70512059)
[449](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=78781413)
[450](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=78781591)
Description:
* Updates made to Tips section on home page in accordance with [419](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70512059)
* Changed wording on Tips section as outlined in ticket [449](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=78781413)
* Fixed improper spelling and punctuation on Rubble Creek confirmation page following ticket [450](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=78781591)
=> BRS: 419, 449, 450

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
Fixes to the workflow files to deploy with SAM.
=> Workflow fixes

.github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-test.yaml
Ticket: [BRS-336](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47054955)
Notes: Bug found during QA: Display the Release Tag or sha instead of the text "gitHubHash" in the footer.
=> BRS-336: Sendbacks

src/app/registration/facility-select/facility-select.component.html, src/app/registration/facility-select/facility-select.component.spec.ts, src/app/registration/facility-select/facility-select.component.ts
Ticket: [BRS-424](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70969356)
- Reference system time from initial facility request to determine if the booking window is valid
- When outside booking window warning will be given to refresh page at appropriate time
- 
-If the time is within booking window user will be able to proceed to next window
=> BRS-424: Passes Bookable prior to 7am

src/app/registration/facility-select/facility-select.component.html
Ticket: [424](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=70969356&issue=bcgov%7Cparks-reso-public%7C424)
Notes: Fixing logic for submitting form when booking window is valid.
=> BRS-424:Fix the logic for booking pass

src/app/registration/success/facilityConfirmation/diamondHead/diamondHeadConfirmation.component.html, src/app/registration/success/facilityConfirmation/garibaldi/cheakamus/cheakamusConfirmation.component.html, src/app/registration/success/facilityConfirmation/garibaldi/rubbleCreek/rubbleCreekConfirmation.component.html, src/app/registration/success/facilityConfirmation/joffreLakes/joffreLakes.component.html
Ticket: [474](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=86991090&issue=bcgov%7Cparks-reso-public%7C474)
Notes: Golden Ears is mentioned in the ticket but since the facility specific messaging has not been completed for this park it would not apply to this ticket since there is no safety information given.
=> BRS-474: Remove information from Safety Heading

.github/workflows/analysis.yaml, src/app/registration/registration.module.ts, src/app/registration/success/facilityConfirmation/mountSeymour/mountSeymour.component.html, src/app/registration/success/facilityConfirmation/mountSeymour/mountSeymour.component.ts, src/app/registration/success/success.component.html, src/app/registration/success/success.component.ts
Ticket: [468](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=83697910&issue=bcgov%7Cparks-reso-public%7C468)
Notes: 
* Added the specific confirmation for Mount Seymour booking success. 
* Updated the logic to determine which park is being used to
* Removed trivvy analysis on PR
=> BRS-468: Mount Seymour Facility Specific Confirmation 

src/app/registration/success/facilityConfirmation/mountSeymour/mountSeymour.component.html
Ticket: [468](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=83697910&issue=bcgov%7Cparks-reso-public%7C468)
Notes: Fixed some typos to complete QA process
=> BRS-468:Mount Seymour Confirmation fix

src/app/footer/footer.component.html, src/app/footer/footer.component.scss
Ticket: [492](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=91284780&issue=bcgov%7Cparks-reso-public%7C492)
Notes: Added land acknowledgement
=> BRS-492: Added land acknowledgement to footer

src/app/services/park.service.ts
BRS-517
#517 
- Update error message for `fetchData`
=> PRDT-517: Update Error Messaging for DUP Public
